/**
 * Test the current schema object generated by `../schema` for equality to the
 * fixture schema file `./fixtures/full_schema.json`. Ensures that any schema
 * refactoring doesn't change its composition.
 */

'use strict';

var path = require( 'path' );
var fixturePath = path.join( __dirname, 'fixtures/full_schema.json' );
var fullSchema = require( fixturePath );
var schema = require( '../schema' );

module.exports = {
  all: function( tape ){
    tape( 'Scheme matches expected.', function ( test ){
      test.deepEqual(
        schema.mappings, fullSchema.mappings,
        'If this fails, you might have to ' +
        'regenerate the schema fixture via `npm run regenerate-schema-fixture`!'
      );
      test.end();
    });
  }
};
