name: Unit Tests
on: workflow_call
jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version: [ 20.x, 22.x, 24.x ]
        icuTokenizer: [true, false]
    steps:
    - uses: actions/checkout@v4
    - name: Install node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run unit tests
      run: |
        npm install
        if [ "${{ matrix.icuTokenizer }}" = "true" ]; then
          jq -n '{ featureFlags: { icuTokenizer: true } }' > $(pwd)/config-icu.json
          export PELIAS_CONFIG=$(pwd)/config-icu.json
        fi
        npm run test